### ISSUE TITLE
Meaningful project: The Physics Hub

### ISSUE THREAD

**Issue by brtymn** [Meaningful-Code/meaningfulcode-frontend#1]
**Project information**
- Name: The Physics Hub
- Website: https://physicshub.herokuapp.com/
- Category: Education
- Source repository: https://github.com/ThePhysHub/ThePhysicsHub

**How is this project meaningful/impactful?**
The Physics Hub is an open source physics simulations project that is being developed by physics students worldwide and aims to deliver clear and easy to understand physics simulations free for everyone!

**How to contribute?**
Any contribution is very welcome! You can create issues about your ideas and suggestions or you can join our Discord community and we will be happy to discuss your contribution!

**Additional context**
Feel free to reach out to the admin on Discord!

**Comment by Pixep** [comment]
Hey @brtymn, thanks, I added your project and it should soon be visible!
Would you mind adding a description and website to your GitHub project? This is what we extract to show on meaningfulcode.org.

Thanks!

**Comment by Pixep** [comment]
Added and visible online.
