### ISSUE TITLE
Meaningful project:  Decidim

### ISSUE THREAD

**Issue by Dynnammo** [Meaningful-Code/meaningfulcode-frontend#24]
**Project information**
- Name: Decidim
- Website: https://decidim.org
- Category: Society
- Source repository: github.com/decidim/decidim

**How is this project meaningful/impactful?**
Decidim is a free open-source participatory democracy platform for cities and organizations. It is a website on which a city, an organization, a company can deploy. Participants can send proposals, amend them, make participatory budgets, online votes and sorting etc.

The platform has more than 15 modules maintained, and a strong community with more than 300 cities or organizations on it.

**How to contribute?**

- Translations : see https://crowdin.com/project/decidim
- Code : see the Github repository [here](github.com/decidim/decidim)
- Ask for new features : meta.decidim.org

**Additional context**
Anything else worth mentioning?

**Comment by Pixep** [comment]
Hey @Dynnammo , sorry for the delay, that is a great project!
Added it to the list. Let me know if there is anything you wish to adjust.

![image](https://user-images.githubusercontent.com/18591372/173262176-5ee14838-a639-4633-a8c9-d743875ee49f.png)
