### ISSUE TITLE
Meaningful project: AgAtAb - bridge over the digital canyon

### ISSUE THREAD

**Issue by pflegende** [Meaningful-Code/meaningfulcode-frontend#29]
**Project information**
- Name:  AgAtAb
- Website: https://demenzpflaster.wordpress.com/2022/04/01/offline-tablet-agatab/
- Category: Accessibility/Health/Society
- Source repository: e.g. GitHub URL
https://github.com/pflegende/agatab
**How is this project meaningful/impactful?**
tries to build a bridge over the digital 🕳️  canyon.
In europe are 50% 50+ people sitting behind this canyon (look for some more information about this in the projects readme)

**How to contribute?**

many

one of this: 
build a sandbox like environment for AgAtAb the (hypothetical) "offline" tablet

other of this:
build a deficit-collecting app with a deep entrance and a high level of fun

**Additional context**
Anything else worth mentioning?

this is 
THIS THING
was hidden yesterday - bring it up!
![Zivilgesellschaft im Landtag](https://user-images.githubusercontent.com/52720420/162535854-cec32a92-8609-4709-b1f3-45ebef277928.png)

**Comment by pflegende** [comment]
https://github.com/pflegende/agatab/issues/1#issuecomment-1072035234

to  [Alexander Seifert](https://alexander-seifert.com) added

**Comment by Pixep** [comment]
Hi @pflegende ! Sorry for the delay, and thank you for the suggestion.
If I got the concept right, I think this is really a good idea.

The content you have is mostly in german, and the GitHub page seems mostly empty, which wouldn't be enough to add it today to our list. However I will be happy to add it at a later point, when it will be easier for people to navigate/understand/contribute to it!

Let me know if this makes sense,
Best regards,
-Adrien
