### ISSUE TITLE
Meaningful project: ClassQuiz

### ISSUE THREAD

**Issue by mawoka-myblock** [Meaningful-Code/meaningfulcode-frontend#68]
**Project information**
- Name: ClassQuiz
- Website: https://classquiz.de
- Category: Education
- Source repository: https://github.com/mawoka-myblock/classquiz

**How is this project meaningful/impactful?**
It's a privacy-friendly alternative to a tool (Kahoot!) used at schools.

**How to contribute?**
Translate: https://translate.mawoka.eu/engage/classquiz/

Other ways: https://github.com/mawoka-myblock/ClassQuiz/blob/master/CONTRIBUTING.md

**Comment by Pixep** [comment]
Thank you @mawoka-myblock , looks like a cool project :), thank you for that!
✅ Project added

**Comment by mawoka-myblock** [comment]
> Thank you @mawoka-myblock , looks like a cool project :), thank you for that! ✅ Project added

Thank you for adding ClassQuiz!
