### ISSUE TITLE
Meaningful project: scaphandre

### ISSUE THREAD

**Issue by bpetit** [Meaningful-Code/meaningfulcode-frontend#8]
**Project information**
- Name: Scaphandre
- Website: https://hubblo-org.github.io/scaphandre
- Category: Environment
- Source repository: https://github.com/hubblo-org/scaphandre

**How to contribute?**
Code, documentation, blog posts, organization of the community, ways to contribute are many.
Here is the contributing guide: https://hubblo-org.github.io/scaphandre/contributing.html

**Additional context**
Scaphandre intends to make measuring and then understanding the energy consumption of tech services easier.
You can only manage what you understand and it seems to us like a very important first step towards a more sustainable tech industry.
Some concrete examples of the metrics you can gather and use thanks to scaphandre: https://metrics.hubblo.org

**Comment by Pixep** [comment]
Hi @bpetit, thank you for this, sorry it took some thinking, but finally decided to go ahead and it.
Thank you for your work! 💪
